"""Increase password_hash length

Revision ID: 1959d70ad889
Revises: d9a1b01f3ca8
Create Date: 2025-08-13 12:16:06.026961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1959d70ad889'
down_revision = 'd9a1b01f3ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
